#!/user/bin/env python
# -*- coding: utf-8 -*-

>>> #!/user/bin/env python
>>> # _*_ coding: utf-8 _*_
>>> 
>>> raw_input('How old is Stevie?  ')
How old is Stevie?  4
'4'
>>> Question_01 = raw_input('How old is Stevie?  ')
How old is Stevie?  4
>>> Question_01
'4'
>>> # task 01 down above
>>> 
>>> raw_input('How many days until Thanksgiving?  ')
How many days until Thanksgiving?  75
'75'
>>> Question_02 = raw_input('How many days until Thanksgiving?  ')
How many days until Thanksgiving?  75
>>> Question_02
'75'
>>> Question_02 = int(raw_input("How many days until Thanksgiving?  "))
How many days until Thanksgiving?  75
>>> Question_02
75
>>> # task 01 complete above
>>> 
>>> 
